spring.application.name=DomingoContratosPetroleoService
server.port=8081
# Configuraci\u00f3n JWT
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration= 3600000

# application.properties
logging.level.org.springframework.security=DEBUG
logging.level.com.CRamirezEvaluacionContratosPetroleo=DEBUG

# Configuraci\u00f3n JWT (ya la tienes)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=3600000

# \u00a1NUEVAS L\u00cdNEAS CLAVE PARA DESHABILITAR JSESSIONID EN URL!
# Fuerza a Tomcat a usar solo cookies para el seguimiento de sesiones
server.servlet.session.tracking-modes=cookie
# Asegura que las cookies de sesi\u00f3n sean HttpOnly (seguridad)
server.servlet.session.cookie.http-only=true
# Asegura que las cookies de sesi\u00f3n sean seguras (solo HTTPS, buena pr\u00e1ctica)
server.servlet.session.cookie.secure=true
# Define la ruta de la cookie de sesi\u00f3n
server.servlet.session.cookie.path=/


spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl